### PR TITLE
Adding new dependency for GitBook

### LINKED ISSUE #264: New Dependency for PDF Generation
I ran into this error earlier today when I was testing the PDF generation script for #259:

Screen Shot 2020-10-14 at 5 43 39 PM

We should update the GitBook instructions to include what appears to be a new dependency introduced with recent content changes.

### PR DESCRIPTION
**Pull request by amyschoen**
Fixes #264

### CODE REVIEW

**Comment by parkerbxyz** [comment]
Thanks, @amyschoen! I wonder if we should update the `generate-pdf` script to install `svgexport` since it already installs `gitbook`:

https://github.com/githubtraining/training-manual/blob/be455ab012d432328e3aa3aeb0a3d9312f1db0df/script/generate-pdf#L8-L9

Maybe something like this:

```diff
- npm install -g gitbook-cli
+ npm install -g gitbook-cli svgexport
```

With that, we could remove those steps from the README. What do you think?

**Comment by amyschoen** [comment]
Not a bad thought @parkerbxyz.  Do we have anyone on Windows who can verify it would still work?  That's the only unknown.

**Comment by allthedoll** [comment]
Hey @amyschoen I just tested in on Windows for you and it works. 😄

**Comment by amyschoen** [comment]
Awesome. Thanks for the verification @allthedoll. I’ll tweak the PR to incorporate that change and remove the instructions update.

**Comment by amyschoen** [comment]
@parkerbxyz and @allthedoll, changes have been made.  Do we want to further alter the instructions to remove the initial gitbook install reference since it's handled by the script already?

**Comment by amyschoen** [comment]
Updated @parkerbxyz

**Review by allthedoll — APPROVED** [review]
🌈 teamwork 🌈

**Review by parkerbxyz — APPROVED** [review]
Thanks, @amyschoen! ✨

**Pull request merged**
