### PR TITLE
Fix default branch

### LINKED ISSUE #321: Detect default branch in class scripts
I ran into the issue of PRs not being created for github-games in production even though the script ran fine when I tested on my test GHES instance.  The culprit ended up being the switch from master to main because my prod instance is still configured to use master.  To work around this in the future and prevent having to do manual changes when syncing .com to GHES, we should add detecting the default branch into create-practice-repos and use that instead of always hardcoding the base of the PR to main.

### PR DESCRIPTION
**Pull request by amyschoen**
Updating so that it uses the default branch in the template repo instead of always assuming a default of main.  This fixes the issue that if your default branch is something other than main, it doesn't add the PRs properly for conflict-practice repos.  This also correctly detects and uses the default branch for the class repo.

I didn't make any changes to reset-game. https://github.com/githubtraining/training-manual/blob/9e66fc09678dedb993526d369e12ca938d4840fe/script/reset-game#L140  Let me know if I should file an issue for us to fix that one up too.

Closes #321

### CODE REVIEW

**Review by Zack9999 — APPROVED** [review]
test

**Comment by parkerbxyz** [comment]
@amyschoen I decided to make my changes on a different branch because they were so extensive. But I branched from this one, so the PR I just opened includes your changes. I hope that’s OK! Here it is: #342.

**Comment by amyschoen** [comment]
Fair enough @parkerbxyz.  I'll test it out later today.

**Comment by amyschoen** [comment]
@parkerbxyz, should we close this one out now that #342 is merged in?

**Comment by parkerbxyz** [comment]
Yeah, we’ll close it since these changes were incorporated in #342.

**Pull request closed without merging**
