### PR TITLE
Error logging

### LINKED ISSUE #290: Error messages not being displayed for repo generation
I had a heck of a time attempting to troubleshoot repo generations mid class this morning.  It looks like one of the more recent changes that introduced the `-s` flag for silent mode also hides errors when they happen in the repo generation scripts.  Here's a snippet from the man page on curl:

```
-s, --silent
              Silent or quiet mode. Don't show progress meter or error
              messages.  Makes Curl mute. It will still output the data
              you ask for, potentially even to the terminal/stdout
              unless you redirect it.

              Use -S, --show-error in addition to this option to disable
              progress meter but still show error messages.

              See also -v, --verbose, --stderr and --no-progress-meter.
```

I'll get the scripts updated to add the `-S` flag, and then do a PR.  We'll want any errors that are occurring to be printed out in the logs.

CC @parkerbxyz

### PR DESCRIPTION
**Pull request by amyschoen**
Adding the -S flag to all the curl commands so that error messages print to the logs when something goes wrong

Closes #290

### CODE REVIEW

**Comment by amyschoen** [comment]
@parkerbxyz, I had a thought when working on this.  We have a lot of curl commands (nearly 100).  Would it make sense to have a helper function for each type of curl command?  If so, I can file a new issue for a refactor.

**Comment by parkerbxyz** [comment]
> @parkerbxyz, I had a thought when working on this. We have a lot of curl commands (nearly 100). Would it make sense to have a helper function for each type of curl command? If so, I can file a new issue for a refactor.

Yes! That would be awesome; great idea! ✨

**Review by parkerbxyz — APPROVED** [review]
This looks great. Thanks, @amyschoen! ✨

**Comment by amyschoen** [comment]
You're welcome @parkerbxyz.  #295 opened so we don't lose track of the refactor suggestion.

**Pull request merged**
