### PR TITLE
Create new shared functions to create issues and pull requests

### LINKED ISSUE #295: Refactor Curl
We have nearly 100 curl calls in the training scripts, but there are only a few variants of the types of commands and flags used.  We should refactor the curl calls as functions in shared_functions to make it easier when we want to slightly tweak our curl commands in the future.

### PR DESCRIPTION
**Pull request by parkerbxyz**
Refactor curl commands (replace `curl` with `HTTPie`) and add dependency checks. Resolves #295.

- [x] Replace cURL with HTTPie
- [x] Add error handling for missing HTTPie dependency
- [x] Add HTTPie dependency installation to bootstrap script

### CODE REVIEW

**Review by laurieatkinson — APPROVED** [review]

**Review by maikadkol — APPROVED** [review]

**Review by Hemanth-Yarlagadda — COMMENTED** [review]
just for learning

**Review by StianVo — APPROVED** [review]

**Review by lishaia — APPROVED** [review]

**Review by IggySantander — DISMISSED** [review]

**Review by wlottering — APPROVED** [review]

**Review by rajatmishra16 — APPROVED** [review]

**Review by nitinpaulk — DISMISSED** [review]
All changes seem right

**Review by edersamirc — APPROVED** [review]
Learning

**Review by edersamirc — APPROVED** [review]

**Review by edersamirc — DISMISSED** [review]

**Review by allthedoll — APPROVED** [review]
Tested, working, and wonderful. ✅ 🦄 👍🏼 🙇🏼‍♀️

**Pull request merged**
