### PR TITLE
Add powershell support

### PR DESCRIPTION
**Pull request by rulasg**
On this PR I am adding Powershell support to the SSH support.

This allows to run Powershell commands in the same scope of the scripts, allowing to use other scripts to help teachers on the management of the attendees activities repos.

Sample [GitHubDevelopersTrainingTeacherScripts](https://www.powershellgallery.com/packages/GitHubDevelopersTrainingTeacherScripts/0.3.6-preview)

cc: @parkerbxyz @amyschoen

### CODE REVIEW

**Comment by rulasg** [comment]
cc: @parkerbxyz @amyschoen

**Review by amyschoen — APPROVED** [review]
👍

**Comment by rulasg** [comment]
Hi @amyschoen please merge the PR as the branch restrictions avoids not authorized users to do so. Thanks.

cc: @parkerbxyz

**Comment by amyschoen** [comment]
Merged @rulasg

**Pull request merged**
