### PR TITLE
Change visibility of practice repos to private

### PR DESCRIPTION
**Pull request by parkerbxyz**
This PR will change the visibility of practice repos from public to private. Since participants receive invitations to join their repository, it shouldn’t need to be public. This should help improve privacy and prevent participants from interacting with the repository before they accept their invitation to join.

### CODE REVIEW

**Comment by beardofedu** [comment]
What is the primary driver for this change? Is it to limit visibility on students / potentially organizations that are participating in our trainings or to make it harder for someone to work in a repository without write access?

**Comment by ericalloyd** [comment]
@parkerbxyz I do use the public visibility as a teaching point to explain why they can access the url and view branches, but cannot create them. 

A benefit would be no one _assuming_ they're a collaborator before accepting their invite, but it would also prevent them from looking around until we get to that onboarding step, which can be a while. I have only had one customer express any concern over the Day 1 repo being public. Have you run into this concern?

**Comment by parkerbxyz** [comment]
> What is the primary driver for this change? Is it to limit visibility on students / potentially organizations that are participating in our trainings or to make it harder for someone to work in a repository without write access?

@beardofedu The primary driver is privacy. The practice repo names include participant GitHub usernames. We should let the participants decide if they want to make their repo public.

> I do use the public visibility as a teaching point to explain why they can access the url and view branches, but cannot create them.

@ericalloyd This change doesn’t affect the Day 1 repository, only the conflict-practice and github-games repositories.

**Review by ericalloyd — APPROVED** [review]
🚀 Concerns addressed. Conflict and Games repos are the students' individual workspaces and it is reasonable that they would not expect them to be public by default.

**Comment by amyschoen** [comment]
@ericalloyd, the day 1 repo is public initially, but the scripts let you make it private if you want when you go to add the slides.  Were they concerned that it was public to start?

**Comment by ericalloyd** [comment]
> > I have only had one customer express any concern over the Day 1 repo being public. Have you run into this concern?
> 
> @ericalloyd, the day 1 repo is public initially, but the scripts let you make it private if you want when you go to add the slides.  Were they concerned that it was public to start?

@amyschoen  Yes, they didn't want their employee usernames in a public repo. They mentioned it in retrospect after the training.

**Comment by amyschoen** [comment]
That makes sense @ericalloyd.  We don't have direct integration on .com, so we all use our own GitHub IDs.  They're not affiliated with our employee usernames.

**Pull request merged**
