### PR TITLE
Updating to make main always the default branch

### LINKED ISSUE #266: Incorrect Default Branch in GHES
When testing the changes in #261 against GHES, I noticed that the default branch can be variable since main isn't officially supported yet.  It ends up being the first branch in alphabetical order if master doesn't exist.  Even though this likely won't be an issue once main is officially supported by GHES, I do think it's a good addition since we'll always know what the default branch is.

This is a quick and easy fix.  We just need to make the call to set the default branch after repo creation since the API can't set it at creation and doesn't keep the same default branch as the template repo.

https://developer.github.com/v3/repos/#update-a-repository

### PR DESCRIPTION
**Pull request by amyschoen**
Explicitly sets the default branch to main after any of the class repos are created.

Fixes #266

### CODE REVIEW

**Comment by amyschoen** [comment]
I think I might've gotten a false positive on the linter by passing a JSON data block in a curl command.  I definitely appreciate suggestions on what I need to do to get things fixed up if I'm misinterpreting what this means:

```
In script/create-game-repos line 121:
  curl -s -i -u "${TOKEN_OWNER}:${TEACHER_PAT}" --data "{\"default_branch\":\"main\"}" -X PATCH "https://${INSTANCE_URL}/repos/${CLASS_ORG}/${STUDENT_REPO}" >>log.out 2>&1
  ^-- SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects.
```

**Comment by amyschoen** [comment]
On second look, it doesn't like the logging redirects.  Those are identical to where we do it elsewhere in the file.  It also seems odd to me that it got flagged in one script that generated student repos and not the other one since that's a copy/paste with no changes.  The class repo is nearly identical as well.  The only difference is the variable reference for repo name.  I must be missing something super subtle.

**Review by parkerbxyz — APPROVED** [review]
Thanks, @amyschoen! 😊

**Comment by amyschoen** [comment]
Thanks for the update @parkerbxyz.  I didn't realize it was the curly braces it didn't like.  Should we update create-games-repo to have curly braces around the variables?  It's been awhile, but I believe we originally added them in for better compatibility with people using Git Bash on Windows.

Nice catch on the `--data` vs `-d` as well.  I think that's more an odd personal quirk on how I use curl.  For some reason, I use short flags for everything but `--data` for the data block.

**Comment by amyschoen** [comment]
Thanks for the commit to fix the linting issue as well @parkerbxyz.  It took me a bit, but I realized when I saw your fix that it didn't like multiple curl commands with logging in a row and wanted them in curly braces with one logging declaration.

**Comment by parkerbxyz** [comment]
> Should we update create-games-repo to have curly braces around the variables?

Perhaps! We can always do that in a different PR to move this one along. Feel free to do the honors of merging this one @amyschoen. 🙇‍♂️

**Comment by amyschoen** [comment]
Wish I could, but you're going to need to do the honors @parkerbxyz.  Someone's going to need to bump up my permissions on the repo for me to merge anything in.

**Pull request merged**
