### PR TITLE
Fix devcontainer/Codespaces

### LINKED ISSUE #377: Codespace creation fails
```
2022-10-23 11:51:03.257Z: Configuration starting...
2022-10-23 11:51:03.816Z: @microsoft/vscode-dev-containers-cli 0.71.0.
2022-10-23 11:51:03.816Z: Start: Resolving Remote
2022-10-23 11:51:03.816Z: $ docker ps -q -a --filter label=Type=codespaces
2022-10-23 11:51:03.842Z: Stop (41 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-10-23 11:51:03.842Z: $ /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/training-manual --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/training-manual/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-10-23 11:51:03.983Z: @devcontainers/cli 0.15.0. Node.js v14.20.0. linux 5.4.0-1090-azure x64.
2022-10-23 11:51:03.983Z: $ docker buildx version
2022-10-23 11:51:04.094Z: Stop (93 ms): Run: docker buildx version
2022-10-23 11:51:04.095Z: github.com/docker/buildx 0.9.1+azure-1 ed00243a0ce2a0aee75311b06e32d33b44729689
2022-10-23 11:51:04.095Z: 
2022-10-23 11:51:04.095Z: Start: Resolving Remote
2022-10-23 11:51:04.095Z: $ docker ps -q -a --filter label=Type=codespaces
2022-10-23 11:51:04.150Z: Stop (58 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-10-23 11:51:04.150Z: local container features stored at: /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node_modules/vscode-dev-containers/container-features
2022-10-23 11:51:04.150Z: $ tar --no-same-owner -x -f -
2022-10-23 11:51:04.206Z: Stop (38 ms): Run: tar --no-same-owner -x -f -
2022-10-23 11:51:04.206Z: * Processing feature: git
2022-10-23 11:51:04.206Z: (!) WARNING: Using the deprecated 'git' Feature. See https://github.com/devcontainers/features/tree/main/src/git#example-usage for the updated Feature.
2022-10-23 11:51:04.656Z: * Processing feature: node
2022-10-23 11:51:04.656Z: (!) WARNING: Using the deprecated 'node' Feature. See https://github.com/devcontainers/features/tree/main/src/node#example-usage for the updated Feature.
2022-10-23 11:51:05.075Z: * Processing feature: python
2022-10-23 11:51:05.075Z: (!) WARNING: Using the deprecated 'python' Feature. See https://github.com/devcontainers/features/tree/main/src/python#example-usage for the updated Feature.
2022-10-23 11:51:05.522Z: * Fetching feature: git_1_oci
2022-10-23 11:51:06.110Z: * Fetching feature: node_2_oci
2022-10-23 11:51:06.726Z: * Fetching feature: python_3_oci
2022-10-23 11:51:07.371Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.15.0-1666525864139/Dockerfile-with-features -t vsc-training-manual-002e2a24ba20de41dfc659940fa836be --target dev_containers_target_stage --build-arg VARIANT=hirsute --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.15.0-1666525864139 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/training-manual/.devcontainer
2022-10-23 11:51:07.708Z: #1 [internal] load .dockerignore
2022-10-23 11:51:07.820Z: #1 ...
2022-10-23 11:51:07.820Z: 
2022-10-23 11:51:07.820Z: #2 [internal] load build definition from Dockerfile-with-features
2022-10-23 11:51:07.820Z: 
2022-10-23 11:51:07.820Z: #2 transferring dockerfile: 1.80kB done
2022-10-23 11:51:07.820Z: 
2022-10-23 11:51:07.821Z: #2 DONE 0.2s
2022-10-23 11:51:07.821Z: 
2022-10-23 11:51:07.821Z: #1 [internal] load .dockerignore
2022-10-23 11:51:07.821Z: #1 transferring context: 2B done
2022-10-23 11:51:07.931Z: #1 DONE 0.3s
2022-10-23 11:51:07.931Z: 
2022-10-23 11:51:07.931Z: #3 resolve image config for docker.io/docker/dockerfile:1.4
2022-10-23 11:51:08.939Z: #3 DONE 1.0s
2022-10-23 11:51:09.108Z: 
2022-10-23 11:51:09.108Z: #4 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
2022-10-23 11:51:09.108Z: #4 resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 0.1s done
2022-10-23 11:51:09.221Z: #4 sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 2.00kB / 2.00kB done
2022-10-23 11:51:09.221Z: #4 sha256:ad87fb03593d1b71f9a1cfc1406c4aafcb253b1dabebf569768d6e6166836f34 528B / 528B done
2022-10-23 11:51:09.221Z: #4 sha256:1e8a16826fd1c80a63fa6817a9c7284c94e40cded14a9b0d0d3722356efa47bd 2.37kB / 2.37kB done
2022-10-23 11:51:09.221Z: #4 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0B / 9.94MB 0.2s
2022-10-23 11:51:09.332Z: #4 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.64MB / 9.94MB 0.3s
2022-10-23 11:51:09.478Z: #4 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.94MB / 9.94MB 0.3s done
2022-10-23 11:51:09.478Z: #4 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546
2022-10-23 11:51:09.732Z: #4 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.2s done
2022-10-23 11:51:10.039Z: #4 DONE 1.0s
2022-10-23 11:51:10.290Z: 
2022-10-23 11:51:10.290Z: #5 [internal] load build definition from Dockerfile-with-features
2022-10-23 11:51:10.290Z: #5 DONE 0.0s
2022-10-23 11:51:10.290Z: 
2022-10-23 11:51:10.290Z: #6 [internal] load .dockerignore
2022-10-23 11:51:10.290Z: #6 DONE 0.0s
2022-10-23 11:51:10.290Z: 
2022-10-23 11:51:10.290Z: #7 [context dev_containers_feature_content_source] load .dockerignore
2022-10-23 11:51:10.291Z: #7 transferring dev_containers_feature_content_source:
2022-10-23 11:51:10.434Z: #7 transferring dev_containers_feature_content_source: 2B done
2022-10-23 11:51:10.434Z: #7 DONE 0.2s
2022-10-23 11:51:10.434Z: 
2022-10-23 11:51:10.434Z: #8 [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/base:0-hirsute
2022-10-23 11:51:10.714Z: #8 DONE 0.5s
2022-10-23 11:51:11.018Z: 
2022-10-23 11:51:11.019Z: #9 [dev_container_auto_added_stage_label 1/2] FROM mcr.microsoft.com/vscode/devcontainers/base:0-hirsute@sha256:c68170fba3bcc2ce8d1d2289d163031bd0c0359a4e18b05b8b1572c5dfbf9a64
2022-10-23 11:51:11.020Z: #9 resolve mcr.microsoft.com/vscode/devcontainers/base:0-hirsute@sha256:c68170fba3bcc2ce8d1d2289d163031bd0c0359a4e18b05b8b1572c5dfbf9a64 0.1s done
2022-10-23 11:51:11.160Z: #9 sha256:c68170fba3bcc2ce8d1d2289d163031bd0c0359a4e18b05b8b1572c5dfbf9a64 743B / 743B done
2022-10-23 11:51:11.160Z: 
2022-10-23 11:51:11.164Z: #9 sha256:b6a7d278ade90dee1f1c8cd85712248901da508936e85a939e1b313359aeaef1 1.37kB / 1.37kB done
2022-10-23 11:51:11.164Z: 
2022-10-23 11:51:11.165Z: #9 sha256:a94c86e28231db9c8c1ce1050b9292f4bf0c8134e519e9ab6e648a84d26dd674 3.12kB / 3.12kB done
2022-10-23 11:51:11.165Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 0B / 31.70MB 0.1s
2022-10-23 11:51:11.304Z: #9 ...
2022-10-23 11:51:11.304Z: 
2022-10-23 11:51:11.305Z: #10 [context dev_containers_feature_content_source] load from client
2022-10-23 11:51:11.305Z: #10 transferring dev_containers_feature_content_source: 342.13kB done
2022-10-23 11:51:11.306Z: #10 DONE 0.3s
2022-10-23 11:51:11.306Z: 
2022-10-23 11:51:11.307Z: #9 [dev_container_auto_added_stage_label 1/2] FROM mcr.microsoft.com/vscode/devcontainers/base:0-hirsute@sha256:c68170fba3bcc2ce8d1d2289d163031bd0c0359a4e18b05b8b1572c5dfbf9a64
2022-10-23 11:51:11.307Z: #9 sha256:1701598239c3ba301af98cdbdc4c053cff70425e0102d03a0a0a660b68520b35 0B / 3.66MB 0.2s
2022-10-23 11:51:11.468Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 7.34MB / 31.70MB 0.4s
2022-10-23 11:51:11.468Z: #9 sha256:1701598239c3ba301af98cdbdc4c053cff70425e0102d03a0a0a660b68520b35 3.66MB / 3.66MB 0.3s done
2022-10-23 11:51:11.468Z: #9 sha256:69e61e03c60557bda70bf3cc9a2dd5562bdd9f66442dd9a5b33f393f7f610ca9 5.43MB / 5.43MB 0.4s
2022-10-23 11:51:11.468Z: #9 sha256:0c7065f004b66d43d33a910871f245130452329a09e1a142a1d6d67ee67cf3b4 6.02kB / 6.02kB 0.4s
2022-10-23 11:51:11.606Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 11.53MB / 31.70MB 0.5s
2022-10-23 11:51:11.607Z: #9 sha256:69e61e03c60557bda70bf3cc9a2dd5562bdd9f66442dd9a5b33f393f7f610ca9 5.43MB / 5.43MB 0.4s done
2022-10-23 11:51:11.607Z: #9 sha256:0c7065f004b66d43d33a910871f245130452329a09e1a142a1d6d67ee67cf3b4 6.02kB / 6.02kB 0.4s done
2022-10-23 11:51:11.607Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 0B / 93.04MB 0.5s
2022-10-23 11:51:11.775Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 16.78MB / 31.70MB 0.6s
2022-10-23 11:51:11.775Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 7.70MB / 93.04MB 0.6s
2022-10-23 11:51:11.915Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 22.02MB / 31.70MB 0.8s
2022-10-23 11:51:11.915Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 25.17MB / 93.04MB 0.8s
2022-10-23 11:51:12.056Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 27.26MB / 31.70MB 1.0s
2022-10-23 11:51:12.057Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 45.09MB / 93.04MB 1.0s
2022-10-23 11:51:12.166Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 31.49MB / 31.70MB 1.1s
2022-10-23 11:51:12.166Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 50.33MB / 93.04MB 1.1s
2022-10-23 11:51:12.369Z: #9 sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 31.70MB / 31.70MB 1.2s done
2022-10-23 11:51:12.474Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 60.98MB / 93.04MB 1.4s
2022-10-23 11:51:12.475Z: #9 extracting sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 0.1s
2022-10-23 11:51:12.587Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 70.67MB / 93.04MB 1.5s
2022-10-23 11:51:12.704Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 83.89MB / 93.04MB 1.6s
2022-10-23 11:51:12.839Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 93.04MB / 93.04MB 1.7s
2022-10-23 11:51:13.259Z: #9 sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 93.04MB / 93.04MB 2.1s done
2022-10-23 11:51:13.483Z: #9 extracting sha256:80d63867ecd7f5e4a966c8400729828e902773a9f03109a2ec69605ddc8045a9 1.1s done
2022-10-23 11:51:13.736Z: #9 extracting sha256:69e61e03c60557bda70bf3cc9a2dd5562bdd9f66442dd9a5b33f393f7f610ca9 0.1s
2022-10-23 11:51:14.098Z: #9 extracting sha256:69e61e03c60557bda70bf3cc9a2dd5562bdd9f66442dd9a5b33f393f7f610ca9 0.4s done
2022-10-23 11:51:14.546Z: #9 extracting sha256:1701598239c3ba301af98cdbdc4c053cff70425e0102d03a0a0a660b68520b35
2022-10-23 11:51:14.799Z: #9 extracting sha256:1701598239c3ba301af98cdbdc4c053cff70425e0102d03a0a0a660b68520b35 0.1s done
2022-10-23 11:51:14.939Z: #9 extracting sha256:0c7065f004b66d43d33a910871f245130452329a09e1a142a1d6d67ee67cf3b4 done
2022-10-23 11:51:15.255Z: #9 extracting sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679
2022-10-23 11:51:18.754Z: #9 extracting sha256:f6b23096c0dc0e18462e99a0afcb609aca1ee16a8b68f37bc16b75d1cb201679 3.6s done
2022-10-23 11:51:21.161Z: #9 DONE 10.1s
2022-10-23 11:51:21.161Z: 
2022-10-23 11:51:21.161Z: #11 [dev_container_auto_added_stage_label 2/2] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive   && apt-get -y install --no-install-recommends     gettext-base=0.21-3ubuntu2   && rm -rf /var/lib/apt/lists/*
2022-10-23 11:51:21.720Z: #11 0.623 Ign:1 http://archive.ubuntu.com/ubuntu hirsute InRelease
2022-10-23 11:51:21.859Z: #11 0.696 Ign:2 http://security.ubuntu.com/ubuntu hirsute-security InRelease
2022-10-23 11:51:21.859Z: #11 0.705 Ign:3 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease
2022-10-23 11:51:22.000Z: #11 0.778 Err:4 http://security.ubuntu.com/ubuntu hirsute-security Release
2022-10-23 11:51:22.000Z: #11 0.778   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.000Z: #11 0.787 Ign:5 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease
2022-10-23 11:51:22.000Z: #11 0.869 Err:6 http://archive.ubuntu.com/ubuntu hirsute Release
2022-10-23 11:51:22.000Z: #11 0.869   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.111Z: #11 0.952 Err:7 http://archive.ubuntu.com/ubuntu hirsute-updates Release
2022-10-23 11:51:22.111Z: 
2022-10-23 11:51:22.111Z: #11 0.952   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.111Z: #11 1.034 Err:8 http://archive.ubuntu.com/ubuntu hirsute-backports Release
2022-10-23 11:51:22.112Z: #11 1.034   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.257Z: #11 1.038 Reading package lists...
2022-10-23 11:51:22.257Z: 
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-updates Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-backports Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 ERROR: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive   && apt-get -y install --no-install-recommends     gettext-base=0.21-3ubuntu2   && rm -rf /var/lib/apt/lists/*]: exit code: 100
2022-10-23 11:51:22.257Z: ------
2022-10-23 11:51:22.257Z:  > [dev_container_auto_added_stage_label 2/2] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive   && apt-get -y install --no-install-recommends     gettext-base=0.21-3ubuntu2   && rm -rf /var/lib/apt/lists/*:
2022-10-23 11:51:22.257Z: #11 0.869   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.257Z: #11 0.952 Err:7 http://archive.ubuntu.com/ubuntu hirsute-updates Release
2022-10-23 11:51:22.257Z: #11 0.952   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.257Z: #11 1.034 Err:8 http://archive.ubuntu.com/ubuntu hirsute-backports Release
2022-10-23 11:51:22.257Z: #11 1.034   404  Not Found [IP: 91.189.91.38 80]
2022-10-23 11:51:22.257Z: #11 1.038 Reading package lists...
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-updates Release' does not have a Release file.
2022-10-23 11:51:22.257Z: #11 1.051 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-backports Release' does not have a Release file.
2022-10-23 11:51:22.257Z: ------
2022-10-23 11:51:22.283Z: ERROR: failed to solve: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive   && apt-get -y install --no-install-recommends     gettext-base=0.21-3ubuntu2   && rm -rf /var/lib/apt/lists/*]: exit code: 100
2022-10-23 11:51:22.283Z: Stop (14910 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.15.0-1666525864139/Dockerfile-with-features -t vsc-training-manual-002e2a24ba20de41dfc659940fa836be --target dev_containers_target_stage --build-arg VARIANT=hirsute --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.15.0-1666525864139 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/training-manual/.devcontainer
2022-10-23 11:51:22.283Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.15.0-1666525864139/Dockerfile-with-features -t vsc-training-manual-002e2a24ba20de41dfc659940fa836be --target dev_containers_target_stage --build-arg VARIANT=hirsute --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.15.0-1666525864139 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/training-manual/.devcontainer
2022-10-23 11:51:22.283Z:     at FF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:281:1584)
2022-10-23 11:51:22.283Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-10-23 11:51:22.283Z:     at async Yf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:280:2899)
2022-10-23 11:51:22.283Z:     at async yb (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:280:1877)
2022-10-23 11:51:22.283Z:     at async NF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:286:2006)
2022-10-23 11:51:22.283Z:     at async so (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:286:3110)
2022-10-23 11:51:22.283Z:     at async kk (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:406:8224)
2022-10-23 11:51:22.283Z:     at async Fk (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:406:7980)
2022-10-23 11:51:22.284Z: Stop (18428 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/training-manual --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/training-manual/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-10-23 11:51:22.284Z: Exit code 1
2022-10-23 11:51:22.284Z: Failed to create container.
2022-10-23 11:51:22.293Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/training-manual --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/training-manual/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-10-23 11:51:22.300Z: Error Code: 1302
2022-10-23 11:51:22.302Z: Container creation failed.
2022-10-23 11:51:22.302Z: 
2022-10-23 11:51:22.307Z: Creating recovery container.
2022-10-23 11:51:36.802Z: Running blocking commands...
```

### PR DESCRIPTION
**Pull request by jessehouwing**
Moves to ubuntu-jammy
Fixes #377

### CODE REVIEW

**Review by parkerbxyz — COMMENTED** [review]
Thanks for this, @jessehouwing! In testing the changes, the container creation was still failing for me. I regenerated the files and made a few more tweaks, and it seems to be working now. Can you confirm the changes work for you?

**Comment by jessehouwing** [comment]
That broke things. Can't spin up this repo on github codespaces:
```
2022-11-01 08:20:15.981Z: #12 5.106 Package httpie is not available, but is referred to by another package.
2022-11-01 08:20:15.981Z: #12 5.106 This may mean that the package is missing, has been obsoleted, or
2022-11-01 08:20:15.981Z: #12 5.106 is only available from another source
2022-11-01 08:20:15.981Z: #12 5.106 
2022-11-01 08:20:15.981Z: #12 5.109 E: Version '3.2.1' for 'httpie' was not found
```

**Comment by parkerbxyz** [comment]
Looks like https://github.com/githubtraining/training-manual/pull/378/commits/555cf5193fc6739445018afbf7ac3656dad94aa1 broke it by specifying the HTTPie version to appease the linter. Should be fixed now. Can you confirm?

**Comment by jessehouwing** [comment]
Yeah, no version fixes things.

**Comment by parkerbxyz** [comment]
Commit [githubtraining/training-manual@`1249f63`](https://github.com/githubtraining/training-manual/pull/378/commits/1249f632e5670260de15e4e74317581901408fcd) should have fixed the problem without removing the HTTPie version. Did you try it before removing the version?

**Comment by jessehouwing** [comment]
I did, computer still said no.

**Comment by dzeyelid** [comment]
Hello, Thank you for updating codespaces environment. I could update my devcontainer environment to Ubuntu jammy with [these updates](https://github.com/githubtraining/training-manual/compare/main...lefthandz-githubtraining:training-manual:update-devcontainer?expand=1). I hope this can help you.

**Comment by jessehouwing** [comment]
Rebuilt the codespace from scratch by deleting it, works now!

**Pull request closed without merging**
